name: CI

on: push

jobs:

  nix-build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: jmc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build dependencies
        run: nix build -L '(import ./pkgs.nix).hsPkgs.shellFor {}'
      - name: Build nix-haskell-test
        run: nix build -L -f pkgs.nix hsPkgs.nix-haskell-test.checks
      - name: Build development tools
        run: nix build -L -f shell.nix
  
